<?php
/** @var \App\User\Model\User $user */
$user = \Base\Context::getInstance()->getUser();
$users = $user->getAllUsers();
?>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Main</title>
</head>
<body>
<?php if (empty($user)) {?>
<ul>
    <li><a href="/login">Войти</a></li>
    <li><a href="/register">Регистрация</a></li>
</ul>
<?php } else { ?>
<header>
    <h4>Hello, <?=$user->name?></h4>
    <ul>
        <li><a href="/logout">Выход</a></li>
        <li><a href="/file">Загрузить файл</a></li>
    </ul>
</header>
    <br><br>
<table border="1">
    <tr>
        <th>Имя</th>
        <th>Возраст</th>
        <th>Статус</th>
    </tr>
    <?php foreach ($users as $user) { ?>
        <tr>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->age ?></td>
            <td><?php echo ($user->age > 17) ? "Совершеннолетний" : "Несовершеннолетний" ?></td>
        </tr>
    <?php } ?>
</table>
<?php } ?>
</body>
</html>