<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration page</title>
</head>
<body>
<h2>Registration page</h2>
<form action="/register" method="post" enctype="multipart/form-data">
    Name: <input type="text" name="login"><br>
    Password: <input type="text" name="password"><br>
    Age: <input type="text" name="age"><br>
    Description: <textarea name="description"></textarea><br>
    Photo: <input type="file" name="photo"><br>
    <input type="submit" value="Registration">
</form>
</body>
</html>