<?php
$file = new \App\File\Model\File();
$photos = $file->photoList($_SESSION['user_id']);
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>File page</title>
</head>
<body>
<form action="/file" method="post" enctype="multipart/form-data">
    <input type="file" name="photo">
    <input type="submit" value="Upload image">
</form>
<br><br>
<table border="1">
    <?php foreach ($photos as $photo) { ?>
        <tr><td><?=$photo->file?></td></tr>
    <?php } ?>
</table>

</body>
</html>